const APP_ACTIONS = {
  GET_FLATS: "GET_FLATS",
  UPDATE_FLATS: "UPDATE_FLATS",
  SET_FLAT_TO_FAV_LIST: "SET_FLAT_TO_FAV_LIST",
  REMOVE_FLAT_FROM_FAV_LIST: "REMOVE_FLAT_FROM_FAV_LIST",
  GET_SEARCH_INPUT: "GET_SEARCH_INPUT",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_TOTAL_PAGES: "SET_TOTAL_PAGES"
};

export { APP_ACTIONS };
